Fix recursive deletion of accounts
slntopp/nocloud pull request #394
Opened 2022-09-22 18:04 UTC by ijimiji

2022-09-23 11:37 UTC, slntopp commented
- [ ] Ensure (all) Credentials are deleted with the account
- [ ] Add Test to specifically test Credentials are purged

2022-09-23 11:37 UTC, slntopp requested changes
see above

2022-09-26 21:52 UTC, ijimiji commented
Just in case I run db manually with 
```docker run -p 8529:8529 -e ARANGO_ROOT_PASSWORD=openSesame arangodb/arangodb:3.9.3```

2022-09-27 10:38 UTC, slntopp approved these changes

2022-09-27 12:17 UTC, merged